### PR TITLE
Feat html view

### PR DESCRIPTION
**Pull request by n-rodriguez**

### CODE REVIEW

**Comment by lbeder** [comment]
Great work, thanks! Please give me a couple days to go over it more thoroughly and also see if I can fix the tests (and slightly raise the coverage) and then I'd merge and release.

**Comment by lbeder** [comment]
I've made a couple of additions here: https://github.com/lbeder/health-monitor-rails/tree/n-rodriguez-feat_html_view. Basically, some minor fixes to make the tests work.

Could you please go over and merge those to your PR and also consider adding a couple of tests for the `:html` and `:xml` response (e.g., checking that some fields are included in the response, similar to what we already do for the `:json` response)?

**Comment by lbeder** [comment]
You can see the passed tests here: https://travis-ci.org/lbeder/health-monitor-rails/builds/208193445

**Comment by n-rodriguez** [comment]
Awesome :) BTW maybe we could use `exclude` directive in travis.yml instead of `allow_failure`. What do you think?

**Comment by lbeder** [comment]
Yeah, the `allow_failure` was a wishful thinking that it'll eventually start passing the tests 😅.

**Comment by lbeder** [comment]
@n-rodriguez thanks again for this feature. Could also add a test for the HTML rendering?

**Comment by n-rodriguez** [comment]
Done :)

**Comment by lbeder** [comment]
Great job! Thanks!

**Comment by lbeder** [comment]
Releasing as 7.0.0.

**Comment by n-rodriguez** [comment]
Thank you!

**Pull request merged**
