### PR TITLE
Refactor Tailwind out of this project

### PR DESCRIPTION
**Pull request by loed-idzinga**
Fixes: #109

Hi there! 

I've taken some time to remove Tailwind CSS from the project, and instead use our own custom CSS.

Some regards:
- I didn't want to use external resources, so I used inline CSS attached to the head of the HTML.
- I tried to stick to the original design as much as possible
- Added a small reset CSS
- Remove all the classes as much as possible

Looking forwards for some feedback @lbeder! 👍

#### Screenshots
Screenshot 2023-10-05 at 11 03 10
Screenshot 2023-10-05 at 11 03 29
Screenshot 2023-10-05 at 11 05 33

### CODE REVIEW

**Comment by lbeder** [comment]
This is amazing! Well done!

For some reason, the CI tests are failing, but it seems due to a CI regression unrelated to your PR. Let me fix it first and then continue from there.

**Comment by lbeder** [comment]
The tests are running now, but there is some regression since the HTML tests require updating as well. Could you take a look?

**Comment by loed-idzinga** [comment]
Ah yes, I've changed the `h3` HTML tags to `h2`. Changed the spec accordingly 👍

**Comment by lbeder** [comment]
Looks great. Thanks! Could you also update the screenshots we show in README.md?

**Comment by loed-idzinga** [comment]
@lbeder I've updated the screenshot 👍

**Comment by lbeder** [comment]
> @lbeder I've updated the screenshot 👍

Amazing! Great stuff! 😄

**Review by lbeder — APPROVED** [review]

**Pull request merged**
