### PR TITLE
adding configurability for external redis checks

### PR DESCRIPTION
**Pull request by ETetzlaff**
Hello everyone, I came across this gem recently and found myself having to add a custom check for external redis urls.  I figured I'd give a shot at implementing it directly into this gem as I would imagine other people could utilize this as well..

Please note, I realize that the attr_accessors are duplicative.  I could use some help resolving that honestly.  For some reason an instance of ::HealthMonitor::Providers::Sidekiq::Configuration would expect the attribute url to be defined despite it not being an attr defined in the class itself.

I didn't want to just start moving things around without getting some maintainer perspective, so I'm hoping to get a little guidance there.

### CODE REVIEW

**Comment by ETetzlaff** [comment]
It seems like Rubocop is biting pretty hard, not sure if a recent release of that has been breaking recent builds or not.

**Comment by ETetzlaff** [comment]
Added a commit to fix rubocop, if not a priority I can pop off that commit.

**Comment by lbeder** [comment]
Hi @ETetzlaff , thanks a lot for your contribution! :)

The `::HealthMonitor::Providers::Sidekiq::Configuration` asking for a `url` seems weird indeed. I'm really swamped with work right now, but I promise to take a look over the weekend (the latest).

Few notes/suggestions:
1. I think that both `.ruby-gemset` and `.ruby-version` shouldn't be checked out, as different people work on this gem using different ruby versions and since we have `appraisal` - it's easy to test it against multiple ruby versions.
2. Could you add the `@url` addition to the README.md as well?
3. Why do you also specify `@latency` for the Redis provider? It doesn't seem to be used.

Again, thanks for the contribution. Looks well and useful! :)

**Comment by ETetzlaff** [comment]
Hi @lbeder thanks for the response.

1. The dot files I committed was a mistake and I'll remove.
2. Yup!
3. I specified @latency for the Redis provider as that is what I had to do but vice versa for the Sidekiq configuration.  I wanted to illustrate the point of what I had to do to achieve successful tests.
4. I can certainly revert that, most of the changes on the PR are now because of rubocop auto fixes, would you prefer me rip that commit off?  If I do, the first build had virtually all builds fail due to some form of complaint from rubocop in the different ruby versions.

**Comment by lbeder** [comment]
Hmmm... so let's (4) for now. When I'll go over the weird configuration issue over the weekend, I'll also try to resolve the Rubocop errors.

**Comment by ETetzlaff** [comment]
@lbeder Made the requested changes including popping off the rubocop commit.  

I'll look around about why they're trying to set those attrs on both configuration, I mainly wanted to get this in front of you before I proposed a possible shift.  If I figure it out, I'll commit to this branch and see what you think.

**Comment by lbeder** [comment]
Sound great! Good luck.

**Comment by lbeder** [comment]
@ETetzlaff, it appears that that weird Redis/Sidekiq configuration issue happened due to a hidden bug in the code - nice catch! I've fixed it in https://github.com/lbeder/health-monitor-rails/commit/33f7d6b66df922946de7afa7466bb52cd148526f, so you can now merge it back and remote the duplicative "test" `attr_accessors`. 

One last note: could you also add to the README.md that configuring Redis' `:url` is optional and if it's won't be configured, then the default connection will be taken instead?

**Comment by ETetzlaff** [comment]
@lbeder Hey thanks for looking into that!  Sorry for my drop off there I was scratching my head around this and didn't see github's email until now.

I've removed the unnecessary attr_accessors now and changed the README as requested.  Let me know if there's anything else you can think of I would be happy to continue helping with this project!

**Comment by lbeder** [comment]
Looks great! I'll merge and release.

**Pull request merged**
