### PR TITLE
Delayed Job Support

### PR DESCRIPTION
**Pull request by orangewolf**
Hi,
  Wanted to see how you felt about adding Delayed::Job support back in to the health monitor.  I've added basic queue size support and thought we'd get a PR open before we go any further in developing it. 

  Totally open to thoughts and feedback.

### CODE REVIEW

**Comment by lbeder** [comment]
Thanks for the contribution, @orangewolf! Could you also update the README.md accordingly? In the meantime, let me sync the `master` branch with the latest version of `rubocop` (which makes the tests to fail for this PR).

**Comment by lbeder** [comment]
Could you also fix the following rubocop offenses?

```
Offenses:
health-monitor-rails.gemspec:34:3: C: Gemspec/OrderedDependencies: Dependencies should be sorted in an alphabetical order within their section of the gemspec. Dependency delayed_job_active_record should appear before sidekiq.
  s.add_development_dependency 'delayed_job_active_record', '>= 4.1'
  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/lib/health_monitor/providers/delayed_job_spec.rb:17:1: C: Layout/EmptyLinesAroundBlockBody: Extra empty line detected at block body beginning.
```

**Comment by orangewolf** [comment]
Updated to add readme and fix rubocop warnings

**Comment by lbeder** [comment]
Can you fix the failing tests? Your PR, unfortunately, still doesn't pass the tests :(

**Comment by lbeder** [comment]
Well done! 👏👏  

I'll merge and release this soon as 8.1.0.

**Pull request merged**
